// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Project struct {
	ID          int32            `db:"id"`
	Name        string           `db:"name"`
	Description string           `db:"description"`
	CreatedAt   pgtype.Timestamp `db:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at"`
}

type TimeEntry struct {
	ID          int32            `db:"id"`
	ProjectID   int32            `db:"project_id"`
	StartTime   pgtype.Timestamp `db:"start_time"`
	EndTime     pgtype.Timestamp `db:"end_time"`
	Duration    pgtype.Int4      `db:"duration"`
	Description string           `db:"description"`
	CreatedAt   pgtype.Timestamp `db:"created_at"`
	UpdatedAt   pgtype.Timestamp `db:"updated_at"`
}

type User struct {
	ID             int32            `db:"id"`
	Provider       string           `db:"provider"`
	ProviderUserID string           `db:"provider_user_id"`
	Email          string           `db:"email"`
	ProfilePicture pgtype.Text      `db:"profile_picture"`
	CreatedAt      pgtype.Timestamp `db:"created_at"`
	UpdatedAt      pgtype.Timestamp `db:"updated_at"`
}
