// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0
// source: time_entry.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createTimeEntry = `-- name: CreateTimeEntry :one
INSERT INTO time_entry (
  project_id, start_time, end_time, description
) VALUES (
  $1, $2, $3, $4
)
RETURNING id, project_id, start_time, end_time, duration, description, created_at, updated_at
`

type CreateTimeEntryParams struct {
	ProjectID   int32            `db:"project_id"`
	StartTime   pgtype.Timestamp `db:"start_time"`
	EndTime     pgtype.Timestamp `db:"end_time"`
	Description string           `db:"description"`
}

func (q *Queries) CreateTimeEntry(ctx context.Context, arg CreateTimeEntryParams) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, createTimeEntry,
		arg.ProjectID,
		arg.StartTime,
		arg.EndTime,
		arg.Description,
	)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StartTime,
		&i.EndTime,
		&i.Duration,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteTimeEntry = `-- name: DeleteTimeEntry :exec
DELETE FROM time_entry
WHERE id = $1
`

func (q *Queries) DeleteTimeEntry(ctx context.Context, id int32) error {
	_, err := q.db.Exec(ctx, deleteTimeEntry, id)
	return err
}

const getTimeEntry = `-- name: GetTimeEntry :one
SELECT id, project_id, start_time, end_time, duration, description, created_at, updated_at FROM time_entry
WHERE id = $1
LIMIT 1
`

func (q *Queries) GetTimeEntry(ctx context.Context, id int32) (TimeEntry, error) {
	row := q.db.QueryRow(ctx, getTimeEntry, id)
	var i TimeEntry
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.StartTime,
		&i.EndTime,
		&i.Duration,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listTimeEntries = `-- name: ListTimeEntries :many
SELECT id, project_id, start_time, end_time, duration, description, created_at, updated_at FROM time_entry
ORDER BY start_time
`

func (q *Queries) ListTimeEntries(ctx context.Context) ([]TimeEntry, error) {
	rows, err := q.db.Query(ctx, listTimeEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TimeEntry
	for rows.Next() {
		var i TimeEntry
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.StartTime,
			&i.EndTime,
			&i.Duration,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateTimeEntry = `-- name: UpdateTimeEntry :exec
UPDATE time_entry
SET start_time = $1,
end_time = $2,
description = $3,
updated_at = CURRENT_TIMESTAMP
WHERE id = $4
`

type UpdateTimeEntryParams struct {
	StartTime   pgtype.Timestamp `db:"start_time"`
	EndTime     pgtype.Timestamp `db:"end_time"`
	Description string           `db:"description"`
	ID          int32            `db:"id"`
}

func (q *Queries) UpdateTimeEntry(ctx context.Context, arg UpdateTimeEntryParams) error {
	_, err := q.db.Exec(ctx, updateTimeEntry,
		arg.StartTime,
		arg.EndTime,
		arg.Description,
		arg.ID,
	)
	return err
}
